[discord]
[discord.protocol]
Token="xxx"
Server="1265341173439008809"
AutoWebhooks=true
RemoteNickFormat="{TENGO}: "
PreserveThreading=true

[whatsapp.protocol]
Number="+62xxx"
SessionFile="session-whatsapp"
QrOnWhiteTerminal=false
RemoteNickFormat="{TENGO}: "

[tengo]
RemoteNickFormat="remotenickformat.tengo"

[api]
[api.minecraft]
BindAddress="0.0.0.0:4242"
Buffer=1000
RemoteNickFormat="{TENGO}: "

[[gateway]]
name="gateway"
enable=true

[[gateway.inout]]
account="discord.protocol"
channel="ID:1268598612083085434"

[[gateway.inout]]
account="whatsapp.protocol"
channel="120363320232619257@g.us"

[[gateway.inout]]
account="api.minecraft"
channel="api"